name: diabuddy
description: "A new Flutter project."
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  gtext: ^0.0.3
  flutter_local_notifications: ^17.1.2
  cupertino_icons: ^1.0.2
  persistent_bottom_nav_bar_v2: ^5.2.3
  flutter_onboarding_slider: ^1.0.11
  font_awesome_flutter: ^10.7.0
  vertical_weight_slider: ^2.6.0
  wheel_slider: ^1.2.1
  semicircle_indicator: ^1.1.1
  fl_chart: ^0.67.0
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_auth: ^4.17.8
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  html: ^0.15.4
  connectivity_plus: ^6.0.3
  image_picker: ^1.1.1
  firebase_storage: ^11.7.6
  pedometer: ^4.0.1
  sensors_plus: ^5.0.1
  shared_preferences: ^2.2.3
  flutter_launcher_icons: ^0.13.1
  permission_handler: ^10.0.0
  rxdart: ^0.27.7
  intl: ^0.17.0
  translator: ^0.1.7
  tflite: ^1.1.2
  flutter_isolate: ^2.0.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo-with-name.png
    - assets/images/logo.png
    - assets/images/profile_empty.png
    - assets/images/google logo.png
    - assets/images/slide_1.png
    - assets/images/meal.jpg
    - assets/meal.json
    - assets/sp2_metadata_v4.tflite

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
