// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCSSnY5S_HSESJcA75UoYbqyCHDeEmOvs',
    appId: '1:535109141123:web:13a3bf66f73438871791b6',
    messagingSenderId: '535109141123',
    projectId: 'diabuddy-7994e',
    authDomain: 'diabuddy-7994e.firebaseapp.com',
    storageBucket: 'diabuddy-7994e.appspot.com',
    measurementId: 'G-KH9GH0J909',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwizktEZDagTs-DrTJmbuhMAme9ehUhUU',
    appId: '1:535109141123:android:8fc2221d4059771a1791b6',
    messagingSenderId: '535109141123',
    projectId: 'diabuddy-7994e',
    storageBucket: 'diabuddy-7994e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgVapRuzHBegcbYoaYdk8bNHVIqoUhF4g',
    appId: '1:535109141123:ios:8a982d4289be7b071791b6',
    messagingSenderId: '535109141123',
    projectId: 'diabuddy-7994e',
    storageBucket: 'diabuddy-7994e.appspot.com',
    iosBundleId: 'com.example.diabuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgVapRuzHBegcbYoaYdk8bNHVIqoUhF4g',
    appId: '1:535109141123:ios:8a982d4289be7b071791b6',
    messagingSenderId: '535109141123',
    projectId: 'diabuddy-7994e',
    storageBucket: 'diabuddy-7994e.appspot.com',
    iosBundleId: 'com.example.diabuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCSSnY5S_HSESJcA75UoYbqyCHDeEmOvs',
    appId: '1:535109141123:web:e8e10a17233fa0151791b6',
    messagingSenderId: '535109141123',
    projectId: 'diabuddy-7994e',
    authDomain: 'diabuddy-7994e.firebaseapp.com',
    storageBucket: 'diabuddy-7994e.appspot.com',
    measurementId: 'G-239XRWHMPG',
  );
}
