// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0y4tapxaUCAQGPhX0aFdS3M8hl_o5GrA',
    appId: '1:1089663472994:web:d44aab98e95cb988eb883b',
    messagingSenderId: '1089663472994',
    projectId: 'lbsomoson1-diabuddy',
    authDomain: 'lbsomoson1-diabuddy.firebaseapp.com',
    storageBucket: 'lbsomoson1-diabuddy.appspot.com',
    measurementId: 'G-0B6Z9N1L52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG48vmADZnG0_8n9ATSz_JtWA__7435Mc',
    appId: '1:1089663472994:android:4505e3dca27653a8eb883b',
    messagingSenderId: '1089663472994',
    projectId: 'lbsomoson1-diabuddy',
    storageBucket: 'lbsomoson1-diabuddy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWiMOt5sB0RVFgQTy8oOw7ND-n3Lcr1nU',
    appId: '1:1089663472994:ios:f2975c790e64e44eeb883b',
    messagingSenderId: '1089663472994',
    projectId: 'lbsomoson1-diabuddy',
    storageBucket: 'lbsomoson1-diabuddy.appspot.com',
    androidClientId: '1089663472994-588dlb504tf7c1b8s7ecvb921uo8hdos.apps.googleusercontent.com',
    iosClientId: '1089663472994-dkkb4959oo03g8dcrielb30d3rfmujft.apps.googleusercontent.com',
    iosBundleId: 'com.example.diabuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWiMOt5sB0RVFgQTy8oOw7ND-n3Lcr1nU',
    appId: '1:1089663472994:ios:f2975c790e64e44eeb883b',
    messagingSenderId: '1089663472994',
    projectId: 'lbsomoson1-diabuddy',
    storageBucket: 'lbsomoson1-diabuddy.appspot.com',
    androidClientId: '1089663472994-588dlb504tf7c1b8s7ecvb921uo8hdos.apps.googleusercontent.com',
    iosClientId: '1089663472994-dkkb4959oo03g8dcrielb30d3rfmujft.apps.googleusercontent.com',
    iosBundleId: 'com.example.diabuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0y4tapxaUCAQGPhX0aFdS3M8hl_o5GrA',
    appId: '1:1089663472994:web:98156416a16847f2eb883b',
    messagingSenderId: '1089663472994',
    projectId: 'lbsomoson1-diabuddy',
    authDomain: 'lbsomoson1-diabuddy.firebaseapp.com',
    storageBucket: 'lbsomoson1-diabuddy.appspot.com',
    measurementId: 'G-WVYM7MY4CY',
  );

}