var classNames = {
  'ADOBO': 'Adobo (Pork & Chicken)',
  'ADOBONG_KANGKONG': 'Adobong Kangkong',
  'AFRITADA': 'Afritada',
  'ARROZ_CALDO': 'Arroz Caldo',
  'BANANA_LATUNDAN': 'Banana, Latundan',
  'BANANA_CUE': 'Banana Cue',
  'BANGUS_FRIED': 'Fried Bangus',
  'BANGUS_INIHAW': 'Inihaw na Bangus',
  'BANGUS_RELLENO': 'Rellenong Bangus',
  'BARBEQUE': 'Barbeque',
  'BEEF_STEAK': 'Beef Steak',
  'BICOL_EXPRESS': 'Bicol Express',
  'BULALO': 'Bulalo',
  'BULANLANG': 'Bulanglang',
  'BURGER_STEAK': 'Burger Steak',
  'CALAMARES': 'Calamares',
  'CALDERETA': 'Caldereta',
  'CANNED_TUNA': 'Canned Tuna',
  'CARBONARA': 'Carbonara',
  'CHAMPORADO': 'Champorado',
  'CHEESEBURGER': 'Cheeseburger',
  'CHICKEN_CURRY': 'Chicken Curry',
  'CHICKEN_INASAL': 'Chicken Inasal',
  'CHICKEN_NUGGETS': 'Chicken Nuggets',
  'CHICKEN_TINOLA': 'Chicken Tinola',
  'CHOPSUEY': 'Chopsuey',
  'COFFEE_3IN1': '3-in-1 Coffee',
  'COFFEE_PURE': 'Coffee Instant, 100% Pure',
  'CORDON_BLEU': 'Cordon Bleu',
  'CORNED_BEEF': 'Corned Beef',
  'CRISPY_PATA': 'Crispy Pata',
  'DINENGDENG': 'Dinengdeng',
  'DINUGUAN': 'Dinuguan',
  'EGG_SCRAMBLED': 'Scrambled Egg',
  'EGG_SUNNYSIDEUP': 'Sunny Sideup',
  'FISH_FILLET': 'Fish Fillet',
  'FISHBALL': 'Fishball',
  'FRIED_CHICKEN': 'Fried Chicken',
  'FRIED_PORKCHOP': 'Fried Porkchop',
  'FRIED_TILAPIA': 'Fried Tilapia',
  'FRENCH_FRIES': 'French Fries',
  'GINATAANG_KALABASA_SITAW': 'Ginataang Kalabasa with Sitaw',
  'GINATAANG_LANGKA': 'Ginataang Langka',
  'GINISANG_AMPLAYA': 'Ginisang Ampalaya',
  'GINISANG_PECHAY': 'Ginisang Pechay',
  'GINISANG_TOGUE_TOKWA': 'Ginisang Togue with Tokwa',
  'GINSANG_SAYOTE': 'Ginisang Sayote',
  'GISING_GISING': 'Gising-Gising',
  'GLAZED_DONUT': 'Glazed Donut',
  'HALO_HALO': 'Halo-Halo',
  'HOTDOG': 'Hotdog',
  'ICED_TEA': 'Iced Tea',
  'KANSI': 'Kansi',
  'KARE_KARE': 'Kare-Kare',
  'LAING': 'Laing',
  'LATTE': 'Latte',
  'LECHON_KAWALI': 'Lechon Kawali',
  'LIEMPO_INIHAW': 'Inihaw na Liempo',
  'LONGGANISA': 'Longganisa',
  'LUMPIANG_SARIWA': 'Lumpiang Sariwa',
  'LUMPIANG_SHANGHAI': 'Lumpiang Shanghai',
  'LUMPIANG_TOGUE': 'Lumpiang Togue',
  'MANGO_HINOG_KALABAW': 'Ripe Mango, Kalabaw',
  'MECHADO': 'Mechado',
  'MENUDO': 'Menudo',
  'MISUA_PATOLA_MEATBALLS': 'Misua with Patola and Meatballs',
  'MONGGO': 'Monggo',
  'NILAGANG_BAKA': 'Nilagang Baka',
  'PAKBET': 'Pakbet',
  'PALABOK': 'Palabok',
  'PANDESAL': 'Pandesal',
  'PANSIT_BIHON': 'Pansit Bihon',
  'PESANG_ISDA': 'Pesang Isda',
  'PORK_SINIGANG': 'Pork Sinigang',
  'SWEET_SOUR_PORK': 'Sweet and Sour Pork',
  'PRITONG_TALONG': 'Pritong Talong',
  'PUTO_PUTI_NIYOG': 'Puto Puti, with Niyog',
  'RED_APPLE': 'Red Apple',
  'RICE': 'White Rice',
  'SINANGAG': 'Sinigang',
  'SIOMAI': 'Siomai',
  'SISIG': 'Sisig',
  'SODA': 'Soda',
  'SOPAS': 'Soda',
  'SPAGHETTI': 'Spaghetti',
  'SQUID_BALL': 'Squidball',
  'SUMAN': 'Suman',
  'TAPA': 'Tapa',
  'TOCINO': 'Tocino',
  'TOKWAT_BABOY': 'Tokwa\'t Baboy',
  'TORTANG_TALONG': 'Tortang Talong',
  'TURON': 'Turon',
  'TUYO': 'Tuyo',
  'UKOY': 'Ukoy',
  'BROWN_RICE': 'Brown Rice',
  'CHOCOLATE_CAKE': 'Chocolate Cake',
  'SHAWARMA': 'Shawarma',
  'LECHE FLAN': 'Leche Flan'
};
